### ISSUE TITLE
Sample circuit is incorrectly rendered

### ISSUE THREAD

**Issue by theRoughCode** [microsoft/quantum-viz.js#17]
The sample circuit is incorrectly rendered such that the operation `Foo` is already expanded on first render. Furthermore, hovering over the group shows a + icon instead of -.

We should investigate this behaviour and fix it.

![image](https://user-images.githubusercontent.com/19257435/120241555-fcc63900-c230-11eb-88cc-90cb8868c8a0.png)

**Comment by anpaz** [comment]
This is a problem on how we keep track of what things are/should be expanded. 
On one side, we use the `GateType.Group` to decide if it should be rendered as a box, on the other hand we use the data-attribute 'expanded' to decided whether a to show the expanded/contracted icon. This should be simplified/consolidated.

**Comment by mqnguyen5** [comment]
Hi, I would like to give this a try if possible. Since I'm pretty new to contributing, where should I start?
