### ISSUE TITLE
trace magic keyword and jupyter horizontal scrolling

### ISSUE THREAD

**Issue by meltyness** [microsoft/quantum-viz.js#51]
I'm troubleshooting an issue observed with %trace keyword and my jupyter installation with the Q# kernel, namely -- I can't seem to get horizontal scrolling to work appropriately.

![image](https://user-images.githubusercontent.com/86126050/161823893-d42c1f03-5a89-4245-b554-af2c699eef49.png)
![image](https://user-images.githubusercontent.com/86126050/161824322-0987c94d-f8ce-4eed-8e6f-a677cab9aa04.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88705bdb-5d04-6a33-1164-eb3bee6b8a0b
* Version Independent ID: cf591262-6c44-08e7-4b3d-43d459fb8c61
* Content: [%trace (magic command) - Q# reference - Microsoft Quantum](https://docs.microsoft.com/en-us/qsharp/api/iqsharp-magic/trace)
* Content Source: [api/iqsharp-magic/trace.md](https://github.com/MicrosoftDocs/quantum-api/blob/live/api/iqsharp-magic/trace.md)
* Product: **qsharp**
* GitHub Login: @anjbur
* Microsoft Alias: **anburton**

**Comment by anpaz** [comment]
thanks for the report @meltyness. we'll try to get this fixed soon.
