### ISSUE TITLE
`@types/prettier` error TS2315: Type 'IsTuple' is not generic.

### ISSUE THREAD

**Issue by aaronthangnguyen** [microsoft/quantum-viz.js#53]
**Describe the bug**
Error TS2315: Type 'IsTuple' is not generic when building production.

**To Reproduce**
1. Run `npm run build:prod`
2. See error

**Expected behavior**
Command should compile successfully without errors

**Screenshots**
<img width="892" alt="Screen Shot 2022-05-17 at 8 59 55 PM" src="https://user-images.githubusercontent.com/37777232/168935853-9d6a7a12-aeb5-450c-9de9-caf521aef09a.png">

**Additional context**
 - OS: Surface Book 2
 - Related issue: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60314

**Comment by aaronthangnguyen** [comment]
@anpaz can we close this issue since it's fixed?

**Comment by anpaz** [comment]
yeap.
